[phases.setup]
nixPkgs = ["dotnet-sdk_8", "icu"]

[phases.install]
cmds = ["dotnet restore"]

[phases.build]
cmds = ["dotnet publish -c Release -o /app/publish"]

[start]
cmd = "dotnet /app/publish/webSitePro.dll --urls http://0.0.0.0:$PORT"